name: push version

on:
  push:
    tags: ["*"]

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-push-version-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    uses: ./.github/workflows/_docker-build.yml
